theme: hyde
title: My Gas Station
url: https://example.com

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin

paginate: 5
permalink: /:year/:month/:day/:title/
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'README.md']
